baseURL = 'https://matthiaswessling.github.io'
languageCode = 'en-us'
title = 'Lorem Ipsum'
theme = 'custom'

[params]
  author = 'Matthias Wessling'
  description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  profileImage = '/images/profile.svg'
  github = 'https://github.com/MatthiasWessling'
  linkedin = 'https://www.linkedin.com/in/matthiaswessling/'
  googlescholar = 'https://scholar.google.com/citations?hl=de&user=ldEjzsgAAAAJ&view_op=list_works&sortby=pubdate'
 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 2

[[menu.main]]
  name = 'Research'
  url = '/research/'
  weight = 3

[[menu.main]]
  name = 'Patents & Products'
  url = '/patents-products/'
  weight = 4

[[menu.main]]
  name = 'Startups'
  url = '/startups/'
  weight = 5

[[menu.main]]
  name = 'News'
  url = '/news/'
  weight = 6

[[menu.main]]
  name = 'Notebooks'
  url = '/notebooks/'
  weight = 7

[[menu.main]]
  name = 'CV'
  url = '/files/cv.pdf'
  weight = 8
  [menu.main.params]
    download = true
