baseURL = 'https://matthiaswessling.github.io'
languageCode = 'en-us'
title = 'Lorem Ipsum'
theme = 'custom'

[params]
  author = 'Lorem Ipsum'
  description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  profileImage = '/images/profile.svg'
  github = 'https://github.com/MatthiasWessling'
  linkedin = 'https://www.linkedin.com/in/lorem-ipsum'
  googlescholar = 'https://scholar.google.com/'
  x = 'https://x.com/lorem_ipsum'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 2

[[menu.main]]
  name = 'Research'
  url = '/research/'
  weight = 3

[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 4

[[menu.main]]
  name = 'Hobbies'
  url = '/hobbies/'
  weight = 5

[[menu.main]]
  name = 'News'
  url = '/news/'
  weight = 6

[[menu.main]]
  name = 'CV'
  url = '/files/cv.pdf'
  weight = 7
  [menu.main.params]
    download = true
